# config/packages/mailer.yaml
framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        stream_options:
            ssl:
                verify_peer: false
                verify_peer_name: false
                allow_self_signed: true
